name: TEMMA
favicon: null
layout_spectrum: 0.876027412712574
typography_spectrum: 0.5591917363926768
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.301984396064654
  lightness: 0.0799690920393914
  saturation: 0.12119110557250679
  rhythmicContrast: 0.4413391179405153
purpose: []
