name: TEMMA
favicon: null
layout_spectrum: 0.2553
typography_spectrum: 0.74085
title: TEMMA HIRASAWA of MOBO
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eee1d1'
    - '#0aa595'
    - '#baa894'
    - '#312c32'
    - '#ad6d4a'
  brandStrength: 0.8125
  lightness: 0.625
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
